### ISSUE TITLE
On server I am getting Gem Load Error is: undefined method `color_field' for class `BootstrapForm::FormBuilder'

### ISSUE THREAD

**Issue by bhushangahire** [bootstrap-ruby/rails-bootstrap-forms#294]
```
[ 2016-09-26 14:03:43.1721 12757/7f4b34089700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/webuser/www/tuition_reimbursement_form/current: An error occurred while starting up the preloader.
  Error ID: bf561a44
  Error details saved to: /tmp/passenger-error-vr8mEb.html
  Message from application: There was an error while trying to load the gem 'bootstrap_form'.
Gem Load Error is: undefined method `color_field' for class `BootstrapForm::FormBuilder'
Backtrace for gem load error is:
/home/webuser/www/tuition_reimbursement_form/shared/vendor/bundle/ruby/2.3.0/gems/bootstrap_form-2.4.0/lib/bootstrap_form/aliasing.rb:22:in `alias_method'
/home/webuser/www/tuition_reimbursement_form/shared/vendor/bundle/ruby/2.3.0/gems/bootstrap_form-2.4.0/lib/bootstrap_form/aliasing.rb:22:in `bootstrap_method_alias'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/bootstrap_form-2.4.0/lib/bootstrap_form/form_builder.rb:47:in `block in <class:FormBuilder>'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/bootstrap_form-2.4.0/lib/bootstrap_form/form_builder.rb:35:in `each'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/bootstrap_form-2.4.0/lib/bootstrap_form/form_builder.rb:35:in `<class:FormBuilder>'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/bootstrap_form-2.4.0/lib/bootstrap_form/form_builder.rb:5:in `<module:BootstrapForm>'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/bootstrap_form-2.4.0/lib/bootstrap_form/form_builder.rb:4:in `<top (required)>'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/home/webuser/www/tuition_reimbursement_form/releases/20160826192944/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
```

**Comment by mattbrictson** [comment]
Can you try upgrading to the latest version of bootstrap_form (2.5.1) and see if that fixes the issue?

**Comment by bhushangahire** [comment]
Will check I mean this version works on One server & development but not on one server. So trying to see if this is a issue with Gem or not.

**Comment by Jasonbit** [comment]
I just installed a Rails 5.0.0.1 app with this latest 2.5.1 gem and I'm seeing the same error in a local development environment.

I previously had this gem install from commit 67e846fd0be74f39dd54e9ea774874913c2f9148, which on any new Rails 5.0.0.1 development installs worked fine.

I'm going to backtrack on this to see what I can find. Love this gem, btw, thank you!

**Comment by Vasfed** [comment]
Still getting this for 2.5.2
```
NameError: undefined method `color_field' for class `BootstrapForm::FormBuilder'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form/aliasing.rb:22:in `alias_method'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form/aliasing.rb:22:in `bootstrap_method_alias'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form/form_builder.rb:47:in `block in <class:FormBuilder>'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form/form_builder.rb:35:in `each'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form/form_builder.rb:35:in `<class:FormBuilder>'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form/form_builder.rb:5:in `<module:BootstrapForm>'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form/form_builder.rb:4:in `<top (required)>'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form.rb:1:in `require'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bootstrap_form-2.5.2/lib/bootstrap_form.rb:1:in `<top (required)>'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/Users/vasfed/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/Users/vasfed/altro/newsite_rails/config/application.rb:7:in `<top (required)>'
/Users/vasfed/altro/newsite_rails/Rakefile:4:in `require'
/Users/vasfed/altro/newsite_rails/Rakefile:4:in `<top (required)>'
```

**Comment by mattbrictson** [comment]
@Vasfed Can you provide a minimal application (e.g. as a public GitHub repo or Gist) that reproduces this issue? I haven't encountered this error and I'm not sure where to start troubleshooting.

**Comment by NDuggan** [comment]
@mattbrictson @Vasfed I can confirm that updating Nokogiri to `1.7.0.1` fixed this issue for me too.

**Comment by mattbrictson** [comment]
I'll consider this issue resolved. Thanks for the info, @NDuggan !
